apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/valkey-io/valkey-helm/valkey
    targetRevision: 0.9.4
    path: .
    helm:
      values: |
        image:
          tag: 9.0.3-alpine3.23
        
        replica:
          enabled: false
          # replicas: 2
          
          # NOTE
          # Does not work without replicas
          #
          # persistence:
          #   size: 1Gi
          #   storageClass: local-path
          #   accessModes:
          #     - ReadWriteOnce
        
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

        # TODO OTEL
        # Ref. https://github.com/valkey-io/valkey-helm/blob/main/valkey/values.yaml
        metrics:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: valkey-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true