apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-de-winter-cert
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: test-de-winter-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - test.de-winter.io