apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tdwio/infra-argocd-tmp
    targetRevision: HEAD
    path: kubernetes/manifests/postgres
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: false