apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/emberstack/helm-charts/reflector
    targetRevision: 10.0.38
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: reflector-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true